# Generated by Django 3.1.8 on 2023-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230512_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.CharField(max_length=1000000),
        ),
    ]
