# Generated by Django 4.2.3 on 2023-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_auto_20230816_0503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
